#!/bin/bash

# used like this:
# i3-msg workspace $(i3-next)
# or like this:
# i3-msg move container to workspace $(i3-next)

focusedws=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused == true).name')
screen=${focusedws:0:1}
number=${focusedws:1}

wsfile=$(mktemp)

i3-msg -t get_workspaces | jq -rS '.[]|.name' | sed -n 's/^'$screen'\(.*\)$/\1/p' | sort -g >$wsfile

# is this the last workspace?
if [ $number == $(tail -1 $wsfile) ]; then
  echo ${screen}$(($number))
else
  # next workspace (the builtin "workspace next" would work ... if it used alphabetical order >.>)
  echo ${screen}$(head -$(( $(grep -nx $number $wsfile | cut -d : -f1) + 1 )) $wsfile | tail -1)
fi

rm $wsfile
