#!/usr/bin/python3

import string
import os
import sys
import time
import subprocess

time.sleep(int(sys.argv[1]))

subprocess.call(['xdotool', 'getactivewindow', 'windowmove', sys.argv[2], sys.argv[3]])
