#!/bin/bash

if [ $# -gt 0 ]; then
rsync -rtuz ~/txt/* $1:~/txt
rsync -rtuz $1:~/txt/* ~/txt
# rsync -rtuz -e 'ssh -p 44741' ~/txt/* $1:~/txt
# rsync -rtuz -e 'ssh -p 44741' $1:~/txt/* ~/txt
else
	echo 'specify target machine as argument'
#rsync -rtuz -e 'ssh -p 44741' ~/txt/* pi@hidden-network:~/txt
#rsync -rtuz -e 'ssh -p 44741' pi@hidden-network:~/txt/* ~/txt
fi
